export const OPTIONS = {
    location: [
        'Village street',
        'Riverbank',
        'Marketplace',
        'City rooftop',
        'Coastal road',
        'Tea garden',
        'Paddy field',
        'Alleyway',
    ],
    timeOfDay: ['Dawn', 'Morning', 'Noon', 'Golden hour', 'Dusk', 'Night'],
    weather: ['Sunny', 'Overcast', 'Rain', 'Drizzle', 'Fog', 'Light haze', 'Stormy'],
    ageGroup: ['Child', 'Teen', 'Young adult', 'Middle-aged', 'Elder'],
    attire: [
        'Lungi',
        'Sari',
        'Salwar kameez',
        'Kurta',
        'Casual modern',
        'Formal',
        'School uniform',
    ],
    role: [
        'Farmer',
        'Shopkeeper',
        'Student',
        'Rickshaw puller',
        'Comedian',
        'Storyteller',
        'Singer',
        'Teacher',
    ],
    shotType: ['Wide', 'Medium', 'Close-up', 'Extreme close-up', 'Establishing'],
    angle: ['Eye-level', 'Low-angle', 'High-angle', 'Over-the-shoulder', 'POV', 'Drone'],
    movement: ['Static', 'Pan', 'Tilt', 'Dolly', 'Truck', 'Handheld', 'Crane'],
    lensStyle: ['Cinematic soft', 'Documentary neutral', 'Vlog', 'Surreal', 'Vintage'],
    aspectRatio: ['16:9', '9:16', '4:5', '1:1', '2.39:1'],
    mood: ['Joyful', 'Nostalgic', 'Dramatic', 'Humorous', 'Suspenseful', 'Contemplative'],
    pacing: ['Slow', 'Medium', 'Fast'],
    colorGrade: ['Warm', 'Cool', 'Natural', 'High-contrast', 'Pastel'],
    language: ['Bangla', 'English', 'Mixed'],
    deliveryStyle: ['Voiceover', 'Dialogue', 'Ambient-only'],
    resolution: ['HD', 'Full HD', '4K'],
    motionFidelity: ['Stable', 'Moderate', 'Expressive'],
    realismLevel: ['High realism', 'Semi-stylized', 'Stylized'],
    safetyRating: ['Family-friendly', 'PG-13', 'Mature'],
};

export const STEPS = [
    { id: 'scene', title: 'Scene Setup', description: 'Describe the environment and ambiance.' },
    { id: 'characters', title: 'Characters', description: 'Define the people in your scene.' },
    { id: 'camera', title: 'Camera & Style', description: 'Set the cinematic and visual tone.' },
    { id: 'emotion', title: 'Emotion & Tone', description: 'Fine-tune the mood and pacing.' },
    { id: 'dialogue', title: 'Dialogue & Sound', description: 'Add sample lines and ambient cues.' },
    { id: 'technical', title: 'Technical', description: 'Set quality and safety constraints.' },
] as const;
